apiVersion: v1
kind: Service
metadata:
   name: voting-service
   namespace: voting-app
spec:
   type: NodePort
   ports:
    - port: 5000
      targetPort: 80
      nodePort: 31000
   selector:
    app: voting-deployment
