apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: voting-deployment
  name: voting-deployment
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: result-deployment
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: examplevotingapp-vote-qhb9j
        resources: {}
status: {}
